# conda version used: 22.11.1
name: marvel
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - libffi=3.4.2
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - openssl=3.2.0
  - pip=23.3.2
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - setuptools=68.2.2
  - tk=8.6.13
  - urllib3=1.26.18
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - asgiref==3.7.2
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backoff==2.2.1
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.2
      - bitarray==2.9.2
      - blinker==1.7.0
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - chroma-bullet==2.2.0
      - chroma-hnswlib==0.7.3
      - chroma-migrate==0.0.7
      - chromadb==0.4.21
      - click==8.1.7
      - clickhouse-connect==0.6.6
      - colbert-ai==0.2.18
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - curl-cffi==0.6.3
      - cycler==0.12.1
      - cython==0.29.37
      - dataclasses-json==0.6.3
      - datasets==2.16.1
      - deprecated==1.2.14
      - dill==0.3.7
      - distro==1.9.0
      - docstring-inheritance==2.2.0
      - duckdb==0.7.1
      - duckduckgo-search==6.0.0
      - exceptiongroup==1.2.0
      - faiss-cpu==1.7.4
      - fastapi==0.108.0
      - filelock==3.13.1
      - filetype==1.2.0
      - flask==3.0.1
      - flatbuffers==23.5.26
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - ftfy==6.2.0
      - fuzzywuzzy==0.18.0
      - git-python==1.0.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - googleapis-common-protos==1.62.0
      - greenlet==3.0.3
      - grpcio==1.64.0
      - h11==0.14.0
      - hdbscan==0.8.37
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.26.0
      - huggingface-hub==0.20.1
      - humanfriendly==10.0
      - idna==3.6
      - imageio==2.33.1
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.1
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kubernetes==28.1.0
      - langchain==0.1.4
      - langchain-community==0.0.16
      - langchain-core==0.1.17
      - langchainhub==0.1.14
      - langsmith==0.0.84
      - lazy-loader==0.3
      - levenshtein==0.23.0
      - lightning==2.1.4
      - lightning-utilities==0.10.1
      - llama-index==0.9.39
      - lxml==5.1.0
      - lz4==4.3.2
      - markdown-it-py==3.0.0
      - marker-pdf==0.2.6
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - mmh3==4.0.1
      - monotonic==1.6
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.4
      - multiprocess==0.70.15
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nougat-ocr==0.1.17
      - numpy==1.26.2
      - oauthlib==3.2.2
      - onnx==1.15.0
      - onnxruntime==1.16.3
      - openai==1.10.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opentelemetry-api==1.22.0
      - opentelemetry-exporter-otlp-proto-common==1.22.0
      - opentelemetry-exporter-otlp-proto-grpc==1.22.0
      - opentelemetry-instrumentation==0.43b0
      - opentelemetry-instrumentation-asgi==0.43b0
      - opentelemetry-instrumentation-fastapi==0.43b0
      - opentelemetry-proto==1.22.0
      - opentelemetry-sdk==1.22.0
      - opentelemetry-semantic-conventions==0.43b0
      - opentelemetry-util-http==0.43b0
      - orjson==3.10.3
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.4
      - pdf2image==1.16.3
      - pdftext==0.3.10
      - pillow==10.2.0
      - posthog==3.1.0
      - protobuf==4.25.1
      - pulsar-client==3.3.0
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==2.7.2
      - pydantic-core==2.18.3
      - pydantic-settings==2.2.1
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pymupdf==1.23.19
      - pymupdfb==1.23.9
      - pyparsing==3.1.2
      - pypdf==3.17.4
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pyreqwest-impersonate==0.4.7
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-levenshtein==0.23.0
      - pytorch-lightning==2.1.4
      - pytube==15.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - qudida==0.0.4
      - ragatouille==0.0.6b4
      - rank-bm25==0.2.2
      - rapidfuzz==3.9.2
      - ray
      - referencing==0.32.0
      - regex==2024.5.15
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rpds-py==0.16.2
      - rsa==4.9
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - ruff==0.1.15
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scipy==1.11.4
      - sconf==0.2.5
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.24
      - srsly==2.4.8
      - starlette==0.32.0.post1
      - streamlit==1.29.0
      - surya-ocr==0.4.5
      - sympy==1.12
      - tabula-py==2.9.0
      - tabulate==0.9.0
      - tenacity==8.2.3
      - texify==0.1.9
      - threadpoolctl==3.2.0
      - tifffile==2024.1.30
      - tiktoken==0.5.2
      - timm==0.5.4
      - tokenizers==0.15.0
      - toml==0.10.2
      - toolz==0.12.0
      - torch==2.2.2
      - torchmetrics
      - torchvision
      - tornado==6.4
      - tqdm==4.66.1
      - transformers==4.36.2
      - typer==0.9.0
      - types-requests==2.31.0.6
      - types-urllib3==1.26.25.14
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - tzlocal==5.2
      - ujson==5.9.0
      - uvicorn==0.25.0
      - validators==0.22.0
      - voyager==2.0.2
      - watchdog==3.0.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.17.0
      - zstandard==0.22.0
