name: marvel
channels:
  - gwoptics
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - libcxx=16.0.6
  - libffi=3.4.2
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.0
  - pip=23.3.2
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.8.1
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - appdirs==1.4.4
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asgiref==3.7.2
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==25.3.0
      - authlib==1.5.2
      - babel==2.17.0
      - backoff==2.2.1
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.2
      - bitarray==2.9.2
      - bleach==6.2.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2025.8.3
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - chroma-bullet==2.2.0
      - chroma-hnswlib==0.7.3
      - chroma-migrate==0.0.7
      - chromadb==0.4.21
      - click==8.1.7
      - clickhouse-connect==0.6.6
      - colbert-ai==0.2.19
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.2.1
      - cryptography==44.0.2
      - curl-cffi==0.6.3
      - cycler==0.12.1
      - cython==0.29.37
      - dataclasses-json==0.6.3
      - datasets==2.16.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.7
      - diskcache==5.6.3
      - distro==1.9.0
      - docstring-inheritance==2.2.0
      - docstring-parser==0.17.0
      - duckdb==0.7.1
      - duckduckgo-search==6.0.0
      - einops==0.8.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.0
      - executing==2.2.0
      - faiss-cpu==1.7.4
      - fast-pytorch-kmeans==0.2.0.1
      - fastapi==0.108.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - filetype==1.2.0
      - flask==3.0.1
      - flatbuffers==23.5.26
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - ftfy==6.2.0
      - fuzzywuzzy==0.18.0
      - git-python==1.0.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - googleapis-common-protos==1.62.0
      - greenlet==3.0.3
      - groq==0.18.0
      - grpcio==1.64.0
      - h11==0.14.0
      - hdbscan==0.8.37
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.26.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.20.1
      - humanfriendly==10.0
      - idna==3.6
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.1
      - instructor==1.10.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.3.2
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.5
      - langchain==0.3.13
      - langchain-community==0.3.13
      - langchain-core==0.3.63
      - langchain-groq==0.2.4
      - langchain-openai==0.3.19
      - langchain-text-splitters==0.3.4
      - langchainhub==0.1.14
      - langgraph==0.2.60
      - langgraph-checkpoint==2.0.9
      - langgraph-sdk==0.1.48
      - langsmith==0.2.4
      - lazy-loader==0.3
      - levenshtein==0.23.0
      - lightning==2.1.4
      - lightning-utilities==0.10.1
      - llama-index==0.9.39
      - lxml==5.1.0
      - lz4==4.3.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - mmh3==4.0.1
      - monotonic==1.6
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - notebook==7.4.4
      - notebook-shim==0.2.4
      - nougat-ocr==0.1.17
      - numpy==1.26.2
      - nvidia-ml-py==12.560.30
      - oauthlib==3.2.2
      - onnx==1.15.0
      - onnxruntime==1.16.3
      - openai==1.102.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opentelemetry-api==1.22.0
      - opentelemetry-exporter-otlp-proto-common==1.22.0
      - opentelemetry-exporter-otlp-proto-grpc==1.22.0
      - opentelemetry-instrumentation==0.43b0
      - opentelemetry-instrumentation-asgi==0.43b0
      - opentelemetry-instrumentation-fastapi==0.43b0
      - opentelemetry-proto==1.22.0
      - opentelemetry-sdk==1.22.0
      - opentelemetry-semantic-conventions==0.43b0
      - opentelemetry-util-http==0.43b0
      - orjson==3.10.3
      - outcome==1.3.0.post0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pdf2image==1.16.3
      - pdfminer-six==20250327
      - pdftext==0.3.10
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - posthog==3.1.0
      - primp==0.9.1
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==4.25.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pulsar-client==3.3.0
      - pure-eval==0.2.3
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pycryptodome==3.22.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.0
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pymupdf==1.23.19
      - pymupdfb==1.23.9
      - pynvml==12.0.0
      - pyparsing==3.1.2
      - pypdf==3.17.4
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pyreqwest-impersonate==0.4.7
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==3.3.0
      - python-levenshtein==0.23.0
      - pytorch-lightning==2.1.4
      - pytube==15.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==27.0.0
      - qudida==0.0.4
      - ragas==0.3.2
      - ragatouille==0.0.8.post4
      - rank-bm25==0.2.2
      - rapidfuzz==3.9.2
      - ray==2.23.0
      - redis==5.0.8
      - referencing==0.32.0
      - regex==2024.5.15
      - requests==2.32.5
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.16.2
      - rsa==4.9
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - ruff==0.1.15
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scipy==1.11.4
      - sconf==0.2.5
      - selenium==4.35.0
      - send2trash==1.8.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sqlalchemy==2.0.24
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.32.0.post1
      - streamlit==1.45.1
      - sympy==1.12
      - tabula-py==2.9.0
      - tabulate==0.9.0
      - tavily-python==0.5.0
      - tenacity==8.2.3
      - terminado==0.18.1
      - texify==0.1.9
      - threadpoolctl==3.2.0
      - tifffile==2024.1.30
      - tiktoken==0.11.0
      - timm==0.5.4
      - tinycss2==1.4.0
      - tokenizers==0.15.0
      - toml==0.10.2
      - tomli==2.2.1
      - toolz==0.12.0
      - torch==2.1.2
      - torchmetrics==1.3.0.post0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.36.2
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typer==0.9.0
      - types-python-dateutil==2.9.0.20250708
      - types-requests==2.31.0.6
      - types-urllib3==1.26.25.14
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - tzlocal==5.2
      - ujson==5.9.0
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.25.0
      - uvloop==0.19.0
      - validators==0.22.0
      - voyager==2.0.2
      - watchdog==3.0.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.14
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.17.0
      - zstandard==0.22.0

